openapi: 3.0.0
info:
  title: BiziQuick API
  version: "1.0.0"
  description: API documentation for the BiziQuick project.

servers:
  - url: http://localhost:5000
    description: Local server

paths: {}

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []
